Repository reactplay/activities, pull requests merged in 2022-10, with the labels that each got.

#79 fix: registration button in small screen devices fixed #76
  components/Header.js
Labels: hacktoberfest

#80 docs: grammatical errors fixed
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#84 update deadline dates
  pages/hackrplay/2022/home.js
  public/Hack-R-Play/BannerLogo.png
  public/Hack-R-Play/NavbarLogo.png
Labels: hacktoberfest

#91 Issue 86 Status filter for idea page
  components/Hack-R-Play/IdeaFilter.js
  components/OwnerFilter.js
  components/StatusFilter.js
  services/graphql/ideas.js
Labels: hacktoberfest, hacktoberfest-accepted

#95 changed redirection method of home page
  next.config.js
  pages/index.js
Labels: hacktoberfest, hacktoberfest-accepted, ready-for-review

#99 Issue-98-hackathon closue , disable add/edit ideas
  archive/pages/hackrplay/2022/registration/[id].js
  archive/pages/hackrplay/2022/registration/index.js
  components/Hack-R-Play/CTA.js
  components/Hack-R-Play/Hero.js
  components/Header.js
  pages/hackrplay/2022/ideas/[id].js
  pages/hackrplay/2022/ideas/index.js
Labels: hacktoberfest, hacktoberfest-accepted
